### ISSUE TITLE
Suggestion: isValidCanonical() Common Factory Method

### ISSUE THREAD

**Issue by chanon** [aarondcohen/id128#13]
Would be nice if there was a method that returned true or false to check whether the given string is a valid UUID/ULID so a try/catch isn't necessary.

**Comment by aarondcohen** [comment]
Good suggestion.  I see a pair of functions that can be added to IdFactory:
- `isCanonical(canonical)`
- `isRaw(raw)`
Both can delegate to `isValidEncoding`.
I'm happy to write it up in a few days or take a PR.

**Comment by aarondcohen** [comment]
Please take a look at https://github.com/aarondcohen/id128/pull/14

**Comment by chanon** [comment]
Looks good!

**Comment by aarondcohen** [comment]
Feature merged with v1.4.0
