### ISSUE TITLE
`.generate()` produces a `Buffer`. All other methods produce a `Uint8Array` representation.

### ISSUE THREAD

**Issue by sunwukonga** [aarondcohen/id128#16]
The `crypto` package method `randomBytes` returns a Buffer that is then stored in `[Symbol(bytes)]`.

All other methods of instantiating put a `Uint8Array` in `[Symbol(bytes)]`.

It seems that comparisons require the `Uint8Array` format, although I haven't used this functionality myself.

I would like to:
 1. change the function of `.generate()` to also return an `Uint8Array`
i.e. in `common/byte-array.js`
```
  generateRandomFilled() {
    return new Uint8Array( randomBytes(MAX_BYTES) );
  }
```
 2. add a getter `buffer` to `BaseId`. 

i.e. in `id/base.js`
```
	get buffer() {
		return Buffer.from( this[_bytes] );
	}
```

**Comment by sunwukonga** [comment]
It might also be nice to add to `id/base.js`
```
  get array() {
    return this[_bytes];
  }
```
that mirrors `.bytes` but with a more intuitive name, while leaving `.bytes` in place for backward compatibility.

**Comment by aarondcohen** [comment]
Good catch on the type mismatch.  Everything is supposed to be Uint8Array so that's definitely a bug.  I'll put up a bug fix shortly.  As for the `.bytes` vs `.array`, I want people to think more about the binary nature of the GUID than the array that holds it.  I really only provide access in case people need to adapt their own interface (bit-packing, alternate encoding, etc).

**Comment by sunwukonga** [comment]
Yeah, it should be `.bytes`. Doing it the way I suggested breaks a rule about naming things after their types; I was just trying to make it a non-breaking change. Since that isn't an issue, there's no point to that footwork ;)

Thanks for the package. I really like the monotonic ulid and how tight and neat it is in both it's binary and canonical forms.

**Comment by aarondcohen** [comment]
Actually, there's no need to fix it since the types are consistent with Liskov substitution:
`Crypto.randomBytes(512) instanceof Uint8Array === true`
However, it will be valuable to downcast the result of `.generate` in the Typescript bindings.
