### ISSUE TITLE
Doesn't work with node 12?

### ISSUE THREAD

**Issue by chanon** [aarondcohen/id128#17]
It seems the module exports don't work like in node 10.

doing 
```
const { Uuid1 } = require('id128')
```
results in Uuid1 being undefined

**Comment by chanon** [comment]
Specifically, the name property doesn't seem to work

```
$ node --version
v12.16.1
$ node -e "const {Ulid} = require('id128'); console.log( 'name = ' + Ulid.name); " 
name =
```


```
$ node --version
v10.19.0
$ node -e "const {Ulid} = require('id128'); console.log( 'name = ' + Ulid.name); " 
name = Ulid
```

**Comment by aarondcohen** [comment]
thanks for reporting.  i will investigate.

**Comment by aarondcohen** [comment]
Thank you for reporting.  It looks like the name field propagates differently for anonymous classes in newer versions.  i have tested a fix and will put up a new version in the next few days.

**Comment by aarondcohen** [comment]
fixed in https://github.com/aarondcohen/id128/pull/19

**Comment by chanon** [comment]
Thank you for the fix!
