### ISSUE TITLE
Add UUID format for ULID

### ISSUE THREAD

**Issue by budarin** [aarondcohen/id128#28]
In databases, the UUID has size advantages in the internal representation compared to the string representation

https://www.postgresql.org/docs/9.1/datatype-uuid.html
https://dba.stackexchange.com/questions/89429/would-index-lookup-be-noticeably-faster-with-char-vs-varchar-when-all-values-are/89433#89433

**Comment by aarondcohen** [comment]
The uuid type is already supported for db reads and writes.  `id.toRaw()` converts the id to hex, which is compliant with one of the uuid standard formats. Use `Ulid.fromRaw` for the reads. There might be a bug on the reads where we need to strip `-` before the conversion.
