### ISSUE TITLE
Possible minification issue with versioned UUID exports?

### ISSUE THREAD

**Issue by BrianSladek** [aarondcohen/id128#29]
We are using this library in a React application built using [Create React App](https://create-react-app.dev/).

We have some code that looks like this:
`import { Ulid, Uuid, Uuid4 } from 'id128';`

In development mode, all of these imports work correctly. However, when the app is built for production, Uuid4 becomes undefined. 

The problem seems related to this code in index.js:
`namespace.Uuid.versioned_ids.reduce(
	(ns, uuid) => Object.assign(ns, {[uuid.name]: uuid}),
	namespace
);`

In development mode, uuid.name correctly contains the name of each versioned UUID, such as "Uuid4", "Uuid6", etc. However, in production, uuid.name outputs "n" for each for some reason. This means the returned namespace contains a single key "n" which maps to one of the versioned UUIDs (whichever comes last). I'm failing to understand why name is just "n" -- maybe someone else has an idea.

This can be easily reproduced using a newly initialized Create React App:
1. Run `npx create-react-app my-app`.
2. In App.js, add this line `import { Uuid4 } from 'id128';`
3. Add `console.log(Uuid4)` somewhere in that file.
4. Run `npm run build`.
5. Run `serve -s build`.
6. Open the console in the running app and note that "undefined" is printed.

I haven't been able to identify the source of the issue. The title is a guess based on this only happening when the app is built and minified.

**Comment by aarondcohen** [comment]
One thought is transpiling might be trying to target an unsupported version of javascript. I make pretty heavy use of symbols so i could see that causing a problem. The other one is the name is generated using  `return this.constructor.name;`.  If the class name is getting minified, i could see that messing with the function.

**Comment by aarondcohen** [comment]
this is definitely an issue the the minifier rewriting the name of the class.  there is a setting to prevent this.  as such, it's not an issue with the library itself.

**Comment by zachintosh** [comment]
Hey, ran into this same issue, using Vite instead of CRA. I'd imagine this will happen with basically any minifier. This would be resolved if the exports for the UUID versions weren't dynamically named (as pointed out in the issue description). Best practice is to only export statically named variables, if possible, since it can cause unforeseen issues like this. I would recommend the library change to statically name exports so each consumer with a minifier doesn't have to individually exclude the library from minification.

Library works great otherwise. Solved a big problem for me.

**Comment by aarondcohen** [comment]
i'm open to PR that will fix it.  it likely means swapping the tests to show that the hardcoded values cover all the supported values:
- https://github.com/aarondcohen/id128/blob/master/test/id128.js#L130
- https://github.com/aarondcohen/id128/blob/master/test/id128.js#L143
