### ISSUE TITLE
Separate modules

### ISSUE THREAD

**Issue by aarondcohen** [aarondcohen/id128#9]
Probably less of an issue for server-side development, but there's a cost to adding new functionality for the client since the files size goes up.  Is it worth providing multiple smaller modules that just export a single id type?

Feedback from developers would be helpful.

**Comment by bjeanes** [comment]
True, but Webpack et al should be able to effectively tree-shake. Definitely an issue if directly being included though.

**Comment by aarondcohen** [comment]
I looked into lernajs and it looks pretty solid.  The biggest considerations to breaking apart the library are:
- within an id family, there's a lot of reuse in the form of inheritance
- some of the uuid functionality requires knowledge of the various algorithms to correctly parse a uuid

If you'd like to take a stab at this let me know.  I'm happy to discuss any issues that arise.
